export { default as Navbar} from './navbar'
export { default as Header} from './header'
export { default as HowItWorks } from './howItWorks'
export { default as UniqueFeatures} from './uniqueFeatures'
export { default as DesignSec} from './designSec'
export { default as MoreFeatures} from './moreFeatures'
export { default as FeedBack} from './feedBack'
export { default as LightFeatures} from './lightFeatures'
export { default as Footer} from './footer'